// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(

    appId: '1:227926549092:web:58bb7d675d713ddfff3571',
    messagingSenderId: '227926549092',
    projectId: 'swimnsmash',
    authDomain: 'swimnsmash.firebaseapp.com',
    storageBucket: 'swimnsmash.firebasestorage.app',
    measurementId: 'G-FM0LZKHGGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    ,
    appId: '1:227926549092:android:4cac5cd74c590d92ff3571',
    messagingSenderId: '227926549092',
    projectId: 'swimnsmash',
    storageBucket: 'swimnsmash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzoKIVJ0pQ_lUkTrECggC9zJbXFQGLe1k',
    appId: '1:227926549092:ios:0e92d6de6d431002ff3571',
    messagingSenderId: '227926549092',
    projectId: 'swimnsmash',
    storageBucket: 'swimnsmash.firebasestorage.app',
    iosBundleId: 'com.example.se380springFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzoKIVJ0pQ_lUkTrECggC9zJbXFQGLe1k',
    appId: '1:227926549092:ios:0e92d6de6d431002ff3571',
    messagingSenderId: '227926549092',
    projectId: 'swimnsmash',
    storageBucket: 'swimnsmash.firebasestorage.app',
    iosBundleId: 'com.example.se380springFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKGQvqncY_kCxnCGcNUsRtwvxK0IoafsI',
    appId: '1:227926549092:web:5bd4a6d0272569a1ff3571',
    messagingSenderId: '227926549092',
    projectId: 'swimnsmash',
    authDomain: 'swimnsmash.firebaseapp.com',
    storageBucket: 'swimnsmash.firebasestorage.app',
    measurementId: 'G-EEG2RKMF9R',
  );
}
